import { BrowserRouter } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Button, Fade, Navigation, Section } from './components';
import { programs, promiseItems, reasons, services } from './content';

export default function App() {
  return <BrowserRouter>
    <Navigation />
    <main id="home">
      <section className="min-h-screen bg-cream px-5 pt-32 md:px-8">
        <div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1fr_.82fr]">
          <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
            <p className="mb-5 text-sm font-semibold uppercase tracking-[.24em] text-navy">Premium Lash Studio</p>
            <h1 className="text-5xl font-semibold leading-[1.04] text-navy md:text-7xl">Wake Up to Naturally Beautiful Lashes.</h1>
            <p className="mt-6 text-2xl text-navy/80">Natural. Elegant. Effortlessly You.</p>
            <p className="mt-6 max-w-xl text-lg leading-8 text-muted">Professional lash treatments designed to enhance your natural beauty with precision and care. Every appointment is thoughtfully tailored to create elegant, long-lasting results that feel comfortable and look effortlessly beautiful.</p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button>Book Appointment</Button><Button outline href="#services">View Services</Button></div>
          </motion.div>
          <Fade delay={0.2}><div className="aspect-[4/5] rounded-[2rem] bg-white p-4 shadow-soft" aria-label="Real Results. Beautifully Natural."><div className="h-full rounded-[1.5rem] bg-gradient-to-br from-white via-cream to-[#e9ded1]" /></div></Fade>
        </div>
      </section>
      <Section id="about" label="About OurLash" title="Enhancing Your Natural Beauty, Never Overpowering It."><div className="grid gap-6 text-lg leading-8 text-muted lg:grid-cols-2"><p>At OurLash, we believe the best beauty treatments don't change who you are—they simply enhance what is already beautiful.</p><p>Every appointment begins with a personal consultation to understand your natural lashes, eye shape, and the look you want to achieve. By tailoring each treatment to your individual features, we create results that feel natural, comfortable, and uniquely yours.</p><p>From consultation to aftercare, every step is carried out with professionalism, high hygiene standards, and genuine attention to detail.</p><p>Our goal is simple: to help you leave with lashes you'll love and confidence you'll carry with you every day.</p></div></Section>
      <Section id="promise" cream label="Our Promise" title="Every Appointment Follows the Same High Standard."><p className="max-w-2xl text-lg leading-8 text-muted">Exceptional results are never accidental.<br /><br />They're built through thoughtful preparation, attention to detail, and a commitment to delivering a consistently enjoyable experience for every client.</p><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{promiseItems.map(([h, d], i) => <Fade delay={i * 0.04} key={h} className="rounded-3xl bg-white p-7 shadow-soft"><span className="text-2xl text-navy">✦</span><h3 className="mt-5 text-xl font-semibold text-navy">{h}</h3><p className="mt-3 leading-7 text-muted">{d}</p></Fade>)}</div></Section>
      <Section id="why-choose-ourlash" label="Why Choose OurLash" title="More Than Just a Lash Appointment."><p className="max-w-2xl text-lg leading-8 text-muted">Beautiful lashes are only part of the experience.<br /><br />From your first consultation to dedicated aftercare support, every detail is thoughtfully designed to provide consistent quality, lasting comfort, and results you'll feel confident wearing every day.</p><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{reasons.map(([h, d]) => <article key={h} className="rounded-3xl border border-divider p-7"><h3 className="text-xl font-semibold text-navy">{h}</h3><p className="mt-3 whitespace-pre-line leading-7 text-muted">{d}</p></article>)}</div><p className="mt-12 max-w-3xl text-xl leading-9 text-navy">Discover the treatment that best suits you and experience lash care designed with quality, comfort, and naturally beautiful results at its heart.</p></Section>
      <Section id="services" cream label="Our Services" title="Thoughtfully Designed Treatments for Naturally Beautiful Lashes."><p className="max-w-3xl text-lg leading-8 text-muted">Every treatment at OurLash is carefully designed to enhance your natural lashes while preserving the unique beauty of your features. Through professional techniques and meticulous attention to detail, we create results that feel elegant, effortless, and beautifully natural.</p><div className="mt-12 grid gap-6 lg:grid-cols-2">{services.map((s) => <article className="rounded-[2rem] bg-white p-8 shadow-soft" key={s.name}><h3 className="text-3xl font-semibold text-navy">{s.name}</h3>{s.description.map((p) => <p key={p} className="mt-5 leading-8 text-muted">{p}</p>)}<div className="my-7 h-px bg-divider" /><p className="text-sm uppercase tracking-[.2em] text-muted">Duration</p><p className="mt-1 font-semibold text-navy">{s.duration}</p><p className="mt-5 text-sm uppercase tracking-[.2em] text-muted">Price</p><p className="mt-1 text-2xl font-semibold text-navy">{s.price}</p><h4 className="mt-7 font-semibold text-navy">What's Included</h4><ul className="mt-3 grid gap-2 text-muted">{s.included.map((x) => <li key={x}>✓ {x}</li>)}</ul><div className="mt-8"><Button>{s.cta}</Button></div></article>)}</div><article className="mt-6 rounded-[2rem] border border-navy/15 bg-white p-8"><span className="rounded-full bg-cream px-4 py-2 text-xs font-bold uppercase tracking-[.2em] text-navy">Coming Soon</span><h3 className="mt-6 text-3xl font-semibold text-navy">Lash Extension</h3><p className="mt-5 max-w-3xl leading-8 text-muted">We're carefully preparing our Lash Extension service with the same commitment to quality, comfort, and attention to detail that defines every OurLash treatment.<br /><br />From application techniques to the overall client experience, every aspect is being thoughtfully developed to ensure exceptional results from day one.<br /><br />Stay tuned.</p></article></Section>
      <Section id="service-area" label="Service Area" title="Professional Lash Care, Wherever You Feel Most Comfortable."><p className="max-w-3xl text-lg leading-8 text-muted">Enjoy the convenience of professional lash treatments from the comfort of your preferred location.<br /><br />Our home service is available in selected areas across Yogyakarta with transparent travel fees, so you'll always know the total cost before confirming your appointment.</p><div className="mt-10 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl bg-cream p-8"><h3 className="text-xl font-semibold text-navy">Areas We Serve</h3><ul className="mt-5 grid gap-3 text-muted"><li>• Sleman</li><li>• Yogyakarta City</li><li>• Bantul</li></ul></div><div className="rounded-3xl border border-divider p-8"><h3 className="text-xl font-semibold text-navy">Travel Fee</h3>{[['0–5 km', 'Free'], ['6–10 km', 'Rp15.000'], ['11–15 km', 'Rp25.000']].map((x) => <div className="mt-5 flex justify-between border-b border-divider pb-3" key={x[0]}><span>{x[0]}</span><strong className="text-navy">{x[1]}</strong></div>)}</div></div><p className="mt-8 max-w-3xl leading-8 text-muted">Travel fees are calculated based on the distance between OurLash and your appointment location.<br /><br />If your address falls outside our service area, please contact us first so we can check availability.</p><div className="mt-8"><Button>Check My Location</Button></div></Section>
      <Section id="programs" cream label="Exclusive Privileges" title="A Small Thank You for Your Trust."><p className="max-w-3xl text-lg leading-8 text-muted">At OurLash, we believe meaningful relationships are built through consistently excellent experiences—not simply through discounts.<br /><br />Our exclusive programs are designed as a genuine expression of appreciation for every client who chooses to trust us with their lash care.</p><div className="mt-12 grid gap-6 md:grid-cols-2">{programs.map(([h, d, b]) => <article key={h} className="rounded-3xl bg-white p-8 shadow-soft">{b && <span className="rounded-full bg-cream px-3 py-2 text-xs font-bold uppercase tracking-[.16em] text-navy">{b}</span>}<h3 className="mt-5 text-2xl font-semibold text-navy">{h}</h3><p className="mt-4 whitespace-pre-line leading-8 text-muted">{d}</p></article>)}</div><p className="mt-12 max-w-3xl text-xl leading-9 text-navy">Your journey with OurLash doesn't end after a single appointment.<br /><br />We hope every visit becomes the beginning of a lasting relationship built on trust, consistent quality, and beautifully natural results.</p></Section>
    </main>
  </BrowserRouter>;
}
